- plot_altair.py
This fixes the live-reloading which would get stuck in an infinite loop otherwise.
> Only regenerate plots when content changes

- CONTRIBUTING.md
- package.json
- requirements.txt
`mknotebooks` fixed their dependency on `nbconvert` so we don't need to install it before.
> Simplify pip dependencies

- docs/custom.css
- mkdocs.yml
- theme/partials/tabs.html
This deduplicates the site navigation so that the tab bar is not repeated on the left sidebar.
I don't have strong feelings about this, but I think I prefer this design since it make it easier to navigate on the docs.
Here is a preview of this design: https://docs-4lbqsgt83.now.sh/
> Deduplicate navigation

- docs/zoo/index.md
It looks like the accuracies quoted here were taken from TensorBoard which might not be 100% accurate since the eval dataset is repeated during training so the last batch of the epoch can include duplicated samples. This PR corrects this by quoting the accuracies from `model.evaluate` with the models downloaded from larq zoo.
> Correct model accuracies

- docs/styles.css
- netron_link.py
This modifies the styling of the netron link to make the appearance consistent with the model summary:
> Improve styling of netron link to make it consistent with model summary

- apidocs.yml
The rename in https://github.com/larq/larq/pull/468 resulted in some quantizers to show up twice in the API docs. This PR hardcodes the names for now to fix it.
> Hardcode Quantizer API docs to remove duplicates

- docs/styles.css
- mkdocs.yml
- model_summary.py
This adds a renderer that will display a collapsible model summary if a docstring adds the following block:
```
'''summary
sota.QuickNet
'''
```
> Add model summary renderer

- docs/zoo/index.md
How I got these numbers:
```python
from larq.models import summary
from larq_zoo.literature import BinaryDenseNet37Dilated, BinaryDenseNet37, BinaryDenseNet28, BinaryResNetE18, BiRealNet, DoReFaNet, XNORNet, BinaryAlexNet
from larq_zoo.sota import QuickNet, QuickNetLarge, QuickNetXL
summary(BinaryDenseNet37Dilated(weights=None))  # for all models
``` 
See each commit for the corresponding model's summary. `QuickNetXL` already had the correct numbers.
Closes #71.
> Update weight and parameter counts in documentation

- now.json
This will ensure that ~~Zeit~~Vercel will always add a trailing slash to the URL which prevents issues that happend previously when navigating on a page that didn't have a trailing slash. E.g. navigation on sites like https://docs.larq.dev/compute-engine would be broken before where as https://docs.larq.dev/compute-engine/ worked as expected.
See https://vercel.com/docs/configuration#project/trailingslash
> Always ensure trailing slashes in URLs 

- docs/zoo/index.md
This PR makes a few small tweaks to the tables on the Zoo landing page:
- Moves the `sota` table above the `literature` table (thanks @daniel-vos)
- Fixes the order of the `literature` table to be descending by Top-1 Accuracy
- Removes the second decimal point in accuracies for models that had them
> Refine Zoo tables

- docs/styles.css
- mkdocs.yml
- requirements.txt
Closes #87 
Before: https://docs.larq.dev/larq/tutorials/mnist/
After: https://docs-mw7c2q9nn.now.sh/larq/tutorials/mnist/
This currently relies on a forked version of mknotebooks since https://github.com/greenape/mknotebooks/pull/28 is awaiting review.
> Improve notebook CSS

- docs/index.md
Since it's been in the CI matrix since larq/larq#469, I think we can add this to the docs as well.
> Add Python 3.8 support to docs

- docs/compute-engine/build_arm.md
It looks like https://github.com/larq/larq/issues/496 and https://github.com/larq/compute-engine/issues/383 might be caused by this confusion so let's make the note in our docs more prominent:
> Make note about 32 vs 64-bit RPi OS more prominent

- docs/zoo/index.md
This should fix the links in the Zoo tables. I've marked this as closing #118, but if you want to keep that open so we can do the (not as easy) aesthetic change of removing "class" and "function" everywhere, we can re-open it after this is merged.
> Fix zoo table links

- docs/zoo/index.md
Reverts larq/docs#120, which was a temporary hack to fix #118, but now got fixed properly by #138.
Closes #118.
> Revert "Fix zoo table links"

- docs/zoo/index.md
This adds LCE benchmarks for literature models on the Pixel 1 (single-threaded). To keep the tables readable, I've removed the parameter count.
> Add LCE benchmarks for literature models

- requirements.txt
This works around https://github.com/tensorflow/metadata/pull/10 to fix our builds
> Pin tensorflow metadata

- .gitignore
`npm run dev` generates a `public/` directory with build assets, that we probably want to exclude.
> Add `/public` to the .gitignore

- docs/compute-engine/api_page_templates/converter.md
I think we can even add TF 2.3.0 in there?
> [LCE] Update supported python and tf versions in converter docs

- docs/compute-engine/build_android.md
- docs/compute-engine/quickstart_android.md
- mkdocs.yml
Moves the part about building a binary under the "building from source" section of the docs, moves the "using the pre-built AAR" and "building AAR locally" sections under a switchable tab, and adds some cross-references to other guides such as #176
> [LCE] Restructure Android guide into different parts

- docs/compute-engine/build/arm.md
This PR splits the different compilation options of the ARM binaries in three different tabs to trim down the size of the build instructions.
Looking at this again, I am actually not 100% sure if this is a readability improvement: [rendered preview](https://docs-6hqhw27c7.vercel.app/compute-engine/build/arm/)
@Tombana what do you think?
> Split different build methods on ARM into different tabs

- package.json
We currently need to build our docs twice to make sure the quantizer plots render correctly. However for the first build we can ignore the model summaries which should speedup the docs build slightly.
> Don't generate model summaries twice

- docs/compute-engine/end_to_end.ipynb
- docs/larq/tutorials/binarynet_cifar10.ipynb
- docs/larq/tutorials/mnist.ipynb
- docs/zoo/tutorials.ipynb
- requirements.txt
We currently allow users to run notebooks on Binder. Binder is great, but unfortunately the Docker build takes quite some time since it needs to install TensorFlow which is discouraging for users.
This PR switches to https://colab.research.google.com/ which has support for GPUs and is commonly used in the TensorFlow ecosystem. I also fixed a few bugs in the larq zoo tutorial which were introduced in a recent keras preprocessing update.
Closes #14
> Switch from Binder to Google Colab for running our tutorials

- docs/styles.css
- mkdocs.yml
This PR implements automatic dark mode, which follows the user's OS-level preference - if your OS is in light mode, the UI will be light and if it's dark it'll be dark. (This only goes into effect after refreshing the page.)
I've also added a new `--larq-green-darker` color, which has the same hue and saturation as `--larq-green` (the logo color) but has brightness 75 instead of 98. This makes it usable for links, which is what I've used it for (links are `--larq-green` on hover.)
The biggest place where you'll see `--larq-green-darker` is in the top navigation bar. I personally think this looks nice, and it can also stay the same between dark and light mode - making the top bar dark/light depending on the mode is a bit trickier since it doesn't stand out properly in dark mode and looked …
> Implement dark mode with automatic switching, and new green accent color

- generate_docs.py
This makes the LCE converter docs a bit more readable.
> Add tf.dtypes.DType to docs aliases

- generate_docs.py
This way it'll show up on /zoo/api/literature, where it's currently missing.
> Add MeliusNet22 to generation script

- docs/compute-engine/end_to_end.ipynb
- netron_link.py
The URL of netron changed which breaks our interactive model visualizations. This PR updates any references to the old URL.
> Fix netron links

- netron_link.py
The CORS proxy we where using isn't available anymore. See https://github.com/Rob--W/cors-anywhere/issues/301#issuecomment-778800455
This PR switches to another service to fix our Netron links.
> Fix netron URLs

- docs/compute-engine/benchmark.md
Earlier the lce_benchmark_model binary was made executable and then transferred to the device (Android phones) and this was failing on Windows. Now, the binary is made executable on the device and it runs as expected.
> making the binary executable on device

- docs/compute-engine/android_example_with_lce.patch
- docs/compute-engine/quickstart_android.md
This updates the instructions for the TFLite android example app in various ways:
1. Clarifies a few minor things in the text.
2. Adds a patch file with all code-changes required in one go.
3. Applies some of the suggestions from [this comment](https://github.com/larq/compute-engine/issues/602#issuecomment-775962340) to make the dependencies-change work again.
4. Disables XNNPACK to resolve the issues [encountered here](https://github.com/larq/compute-engine/issues/602).
5. Adds instructions on how to select the right API as also [described here](https://github.com/larq/compute-engine/issues/636).
6. Replaces Bintray release support with manual downloading from the GitHub release page.
This was all tested together and I managed to classify a banana with my phone:
Review tip: enable `Hide …
> Update instructions for the Android example app

- docs/compute-engine/build/arm.md
Recently we updated LCE to the TensorFlow version 2.8.0, which deprecated the make-build system and replaced it with CMake. We also [made those changes in LCE](https://github.com/larq/compute-engine/pull/722). This PR updates the docs accordingly.
Furthermore, it removes the cross-compilation without Bazel option, since that did not work out-of-the-box for me with CMake. If you don't think we should remove this I'll investigate further.
> Update arm compilation docs

- theme/main.html
According to https://usefathom.com/docs/script/custom-domains this change is necessary.
> Fix fathom tracking script
